/* Program: adsl_qc.sas */
/* Independent double-programming QC re-derivation of adsl.sas */
/* Generated by SpecGen */

/* Same pre-step datasets adsl.sas's own main step merges — see module docstring */
data adsl_qc;
  merge dm ex_dates ex_first suppdm_w se_epoch ds_summary ds_trtdisc vs_summary cm_summary mh_summary;
  by usubjid;

/* AGEGR1: Pooled Age Group 1 */
data _null_;
    if missing(AGE) then do;
        AGEGR1 = '';
    end; else if AGE < 65 then do;
        AGEGR1 = '<65';
    end; else if AGE <= 80 then do;
        AGEGR1 = '65-80';
    end; else do;
        AGEGR1 = '>80';
    end;
run;

/* AGEGR1N = Pooled Age Group 1 (N) */
length AGEGR1N 8;
label AGEGR1N 'Pooled Age Group 1 (N)';
format AGEGR1N Z2.;
select(AGEGR1);
    when("<65") AGEGR1N = 1;
    when("65-80") AGEGR1N = 2;
    when(">80") AGEGR1N = 3;
endselect;

/* TRT01P Planned Treatment for Period 01 */
TRT01P = DM.ARM;

/* TRT01PN is an integer variable representing the planned treatment for Period 01 (N). */

if missing(TRT01P) then do;
    TRT01PN = .; /* Missing value if TRT01P is missing */
end;
else if TRT01P = 'Placebo' then TRT01PN = 0;
else if TRT01P = 'Drug A 50mg' then TRT01PN = 1;
else if TRT01P = 'Drug A 100mg' then TRT01PN = 2;
else do; /* Invalid value */
    TRT01PN = .; /* Missing value for invalid values */
end;

/* TRTDURD = Total Treatment Duration (Days) */
if missing(TRTEDT) or missing(TRTSDT) then TRTDURD = .;
else TRTDURD = input(substr(TRTEDT,1,10), yymmdd8.) - input(substr(TRTSDT,1,10), yymmdd8.) + 1;

EPOCHFL text 1

EPOCHFL = if missing(TRTEPSDT) then 'N' else 'Y';

/* COMPFL is 'Y' if SUPPDM QNAM=COMPLT has QVAL of "Y"; else 'N'. */
data _null_;
    set study_data;  * Replace with the actual dataset name;
    
    length COMPFL $1;

    select;
        when (QNAM = "COMPLT" and QVAL = "Y") COMPFL = "Y";
        otherwise COMPFL = "N";
    end;

    stop;
run;

/* Safety Population Flag */
SAFFL = 'N';
if not missing(TRTSDT) then SAFFL = 'Y';

/* ITTFL: Intent-To-Treat Population Flag */
data _null_;
    if missing(ARM) or ARM = "Screen Failure" then ITTFL = 'N';
    else ITTFL = 'Y';
run;

run;