/* Program: adsl_compare.sas */
/* Reconciles adsl (production) against adsl_qc (independent QC re-derivation) */
/* Generated by SpecGen — deterministic, no model call */

proc sort data=adsl(keep=USUBJID AGEGR1 AGEGR1N TRT01P TRT01PN TRTDURD EPOCHFL COMPFL SAFFL ITTFL) out=_prod; by USUBJID; run;
proc sort data=adsl_qc(keep=USUBJID AGEGR1 AGEGR1N TRT01P TRT01PN TRTDURD EPOCHFL COMPFL SAFFL ITTFL) out=_qc; by USUBJID; run;

proc compare base=_prod compare=_qc listall method=exact out=_compare_diffs outnoequal;
  id USUBJID;
  var AGEGR1 AGEGR1N TRT01P TRT01PN TRTDURD EPOCHFL COMPFL SAFFL ITTFL;
run;

/* _compare_diffs has one observation per subject/variable that disagreed
   between production and QC; the LISTING output above also prints a full
   PROC COMPARE report. No rows in _compare_diffs (and "NOTE: No unequal
   values were found" in the log) means the two independent derivations
   agree for every subject and every variable checked (AGEGR1 AGEGR1N TRT01P TRT01PN TRTDURD EPOCHFL COMPFL SAFFL ITTFL). */
