# ********************************
# Program: adsl.R
# Generated by SpecGen (target = r)
# Plain tidyverse; same spec as adsl.sas (independent implementation)
# ********************************
library(dplyr)
library(tidyr)

# Pre-step 1: dosing records, earliest first
ex_dosed <- ex |>
  filter(EXDOSE > 0, EXSTDTC != "") |>
  arrange(USUBJID, EXSTDTC)

# Pre-step 2: treatment from the first dosing record
ex_first <- ex_dosed |>
  group_by(USUBJID) |>
  slice(1) |>
  ungroup() |>
  transmute(USUBJID, TRT01A = EXTRT)

# Pre-step 3: first and last dosing dates per subject
ex_dates <- ex |>
  filter(EXDOSE > 0) |>
  group_by(USUBJID) |>
  summarise(
    TRTSDT  = min(as.Date(substr(EXSTDTC, 1, 10)), na.rm = TRUE),
    TRTSDTM = min(as.POSIXct(EXSTDTC, format = "%Y-%m-%dT%H:%M:%S", tz = "UTC"), na.rm = TRUE),
    TRTEDT  = max(as.Date(substr(EXENDTC, 1, 10)), na.rm = TRUE),
    .groups = "drop"
  )

# Pre-step 4: transpose SUPPDM (tall) to one row per subject (wide)
suppdm_w <- suppdm |>
  select(USUBJID, QNAM, QVAL) |>
  pivot_wider(names_from = QNAM, values_from = QVAL)

# Pre-step 5: treatment epoch dates from SE (ETCD = TRT)
se_epoch <- se |>
  filter(ETCD == "TRT") |>
  arrange(USUBJID, SESTDTC) |>
  group_by(USUBJID) |>
  slice(1) |>
  ungroup() |>
  transmute(
    USUBJID,
    TRTEPSDT = as.Date(substr(SESTDTC, 1, 10)),
    TRTEPEDT = as.Date(substr(SEENDTC, 1, 10))
  )

# Pre-step 6: end-of-study disposition (DS)
ds_summary <- ds |>
  filter(DSCAT == "DISPOSITION EVENT", is.na(DSSCAT) | DSSCAT == "") |>
  arrange(USUBJID, DSSTDTC) |>
  group_by(USUBJID) |>
  slice(1) |>
  ungroup() |>
  mutate(
    EOSSTT   = if_else(DSDECOD == "COMPLETED", "COMPLETED", "DISCONTINUED"),
    EOSDT    = as.Date(substr(DSSTDTC, 1, 10)),
    DCSREAS  = if_else(EOSSTT == "DISCONTINUED", DSDECOD, NA_character_),
    DCSREASP = if_else(EOSSTT == "DISCONTINUED", DSTERM,  NA_character_)
  ) |>
  select(USUBJID, EOSSTT, EOSDT, DCSREAS, DCSREASP)

# Pre-step 7: treatment discontinuation date (DS, DSSCAT='STUDY TREATMENT')
ds_trtdisc <- ds |>
  filter(DSCAT == "DISPOSITION EVENT", DSSCAT == "STUDY TREATMENT", DSDECOD != "COMPLETED") |>
  arrange(USUBJID, DSSTDTC) |>
  group_by(USUBJID) |>
  slice(1) |>
  ungroup() |>
  transmute(USUBJID, DCTDT = as.Date(substr(DSSTDTC, 1, 10)))

# Pre-step 8: baseline vitals from VS (VSBLFL='Y')
vs_summary <- vs |>
  filter(VSBLFL == "Y", VSTESTCD %in% c("BMI", "HEIGHT", "WEIGHT")) |>
  select(USUBJID, VSTESTCD, VSSTRESN) |>
  pivot_wider(names_from = VSTESTCD, values_from = VSSTRESN) |>
  rename(BMIBL = BMI, HEIGHTBL = HEIGHT, WEIGHTBL = WEIGHT)

# Pre-step 9: CM existence flags
cm_summary <- cm |>
  group_by(USUBJID) |>
  summarise(
    CMFL   = if_else(any(CMCAT %in% c("PRIOR", "CONCOMITANT")), "Y", "N"),
    CMINFL = if_else(any(CMCAT == "PRIOR"), "Y", "N"),
    .groups = "drop"
  )

# Pre-step 10: MH existence flag
mh_summary <- mh |>
  group_by(USUBJID) |>
  summarise(
    MHFL = if_else(any(MHCAT == "PRIMARY DIAGNOSIS" & MHENRF == "ONGOING"), "Y", "N"),
    .groups = "drop"
  )

# Main step: join DM with every pre-step summary
adsl <- dm |>
  left_join(ex_dates,   by = "USUBJID") |>
  left_join(ex_first,   by = "USUBJID") |>
  left_join(suppdm_w,   by = "USUBJID") |>
  left_join(se_epoch,   by = "USUBJID") |>
  left_join(ds_summary, by = "USUBJID") |>
  left_join(ds_trtdisc, by = "USUBJID") |>
  left_join(vs_summary, by = "USUBJID") |>
  left_join(cm_summary, by = "USUBJID") |>
  left_join(mh_summary, by = "USUBJID") |>
  mutate(
    # -- BEGIN AGEGR1 -- #
    # Pooled Age Group 1
    
    AGEGR1 = dplyr::case_when(
      is.na(AGE) ~ NA_character_,
      AGE < 65 ~ "<65",
      between(AGE, 65, 80) ~ "65-80",
      AGE > 80 ~ ">80"
    ),
    # -- END AGEGR1 -- #
    # -- BEGIN SEXN -- #
    # Convert SEX to numeric code
    SEXN = dplyr::case_when(
      SEX == "M" ~ 1,
      SEX == "F" ~ 2,
      TRUE ~ NA_real_
    ),
    # -- END SEXN -- #
    # -- BEGIN RACEN -- #
    # Convert RACE to numeric code
    RACEN = dplyr::case_when(
      RACE == "WHITE" ~ 1,
      RACE == "BLACK OR AFRICAN AMERICAN" ~ 2,
      RACE == "ASIAN" ~ 3,
      RACE == "AMERICAN INDIAN OR ALASKA NATIVE" ~ 4,
      RACE == "OTHER" ~ 5,
      TRUE ~ NA_real_
    ),
    # -- END RACEN -- #
    # -- BEGIN BMIBLGR1 -- #
    # Baseline BMI Group
    BMIBLGR1 = dplyr::case_when(
      is.na(BMIBL) ~ NA_character_,
      BMIBL < 25 ~ "<25",
      BMIBL >= 30 ~ ">=30",
      TRUE ~ "25-<30"
    ),
    # -- END BMIBLGR1 -- #
    # -- BEGIN TRT01P -- #
    # Planned Treatment for Period 01
    TRT01P = if_else(is.na(ARM), NA_character_, ARM),
    # -- END TRT01P -- #
    # -- BEGIN TRT01AN -- #
    # TRT01AN: Numeric code for TRT01A
    TRT01AN = case_when(
        ARM == "Placebo" ~ 0,
        ARM == "Drug A 50mg" ~ 1,
        ARM == "Drug A 100mg" ~ 2,
        TRUE ~ NA_real_
    ),
    # -- END TRT01AN -- #
    # -- BEGIN TRTDURD -- #
    # Total Treatment Duration (Days)
    TRTDURD = case_when(
      is.na(TRTEDT) | is.na(TRTSDT) ~ NA_real_,
      TRUE ~ as.integer(as.Date(substr(TRTEDT, 1, 10)) - as.Date(substr(TRTSDT, 1, 10))) + 1
    ),
    # -- END TRTDURD -- #
    # -- BEGIN COMPFL -- #
    # Study Completion Flag  
    COMPFL = if_else(is.na(EOSSTT), NA_character_, case_when(
        EOSSTT == "COMPLETED" ~ "Y",
        TRUE ~ "N"
    )),
    # -- END COMPFL -- #
    # -- BEGIN DTHDT -- #
    # Date of Death: Extract date part from DTHDTC or set to NA if missing or partial
    DTHDT = dplyr::case_when(
      is.na(DTHDTC) ~ as.Date(NA),
      substr(DTHDTC, 1, 10) == "" ~ as.Date(NA),
      TRUE ~ as.Date(substr(DTHDTC, 1, 10), format="%Y-%m-%d")
    ),
    # -- END DTHDT -- #
    # -- BEGIN SAFFL -- #
    # Safety Population Flag
    SAFFL = if_else(!is.na(TRTSDT), "Y", "N"),
    # -- END SAFFL -- #
    # -- BEGIN ITTFL -- #
    # ITTFL = Intent-To-Treat Population Flag
    ITTFL = dplyr::case_when(
      is.na(ARM) ~ NA_character_,
      ARM == "Screen Failure" ~ NA_character_,
      TRUE ~ "Y"
    ),
    # -- END ITTFL -- #
    # -- BEGIN PPROTFL -- #
    PPROTFL = case_when(
      ITTFL == "Y" & EOSSTT == "COMPLETED" & COMPFL == "Y" ~ "Y",
      TRUE ~ "N"
    ),
    # -- END PPROTFL -- #
    # -- BEGIN ENRLFL -- #
    # ENRLFL - Enrolled Population Flag
    ENRLFL = case_when(!is.na(RFICDTC) ~ "Y", TRUE ~ "N"),
    # -- END ENRLFL -- #
    # -- BEGIN RANDFL -- #
    RANDFL = case_when(!is.na(RANDDT) ~ "Y", TRUE ~ "N"),
    # -- END RANDFL -- #
    # -- BEGIN RFICDT -- #
    # Date of Informed Consent
    RFICDT = case_when(
      is.na(RFICDTC) ~ as.Date(NA),
      TRUE ~ as.Date(substr(RFICDTC, 1, 8), format = "%Y%m%d")
    ),
    # -- END RFICDT -- #
    # -- BEGIN DURDSGR1 -- #
    # Duration of Disease Group
    DURDSGR1 = dplyr::case_when(
      is.na(DURDISM) ~ NA_character_,
      DURDISM < 12 ~ "<1 year",
      DURDISM >= 36 ~ ">=3 years",
      TRUE ~ "1-<3 years"
    ),
    # -- END DURDSGR1 -- #
    # -- BEGIN RANDDY -- #
    # RANDDY <- case_when(
    #   is.na(RANDDT) | is.na(SCRPDT) ~ NA_real_,
    #   as.numeric(as.Date(substr(RANDDT, 1, 10))) >= as.numeric(as.Date(substr(SCRPDT, 1, 10))) ~
    #     as.numeric(as.Date(substr(RANDDT, 1, 10))) - as.numeric(as.Date(substr(SCRPDT, 1, 10))) + 1,
    #   TRUE ~ as.numeric(as.Date(substr(RANDDT, 1, 10))) - as.numeric(as.Date(substr(SCRPDT, 1, 10)))
    # )
    RANDDY = NA_real_,  # WRITER PRODUCED NO CODE for this derivation
    # -- END RANDDY -- #
    # -- BEGIN DTHDY -- #
    # Day of Death Relative to First Dose
    DTHDY = case_when(
      is.na(DTHDT) | is.na(TRTSDT) ~ NA_real_,
      DTHDT >= TRTSDT ~ as.numeric(DTHDT - TRTSDT) + 1,
      TRUE ~ as.numeric(DTHDT - TRTSDT)
    ),
    # -- END DTHDY -- #
    # -- BEGIN EOSDY -- #
    # Day of End of Study Relative to First Dose
    EOSDY = case_when(
      is.na(EOSDT) | is.na(TRTSDT) ~ NA_real_,
      EOSDT >= TRTSDT ~ as.numeric(EOSDT - TRTSDT) + 1,
      TRUE ~ as.numeric(EOSDT - TRTSDT)
    ),
    # -- END EOSDY -- #
    # -- BEGIN EPOCHFL -- #
    # Entered Treatment Epoch Flag
    EPOCHFL = if_else(!is.na(TRTEPSDT), "Y", "N"),
    # -- END EPOCHFL -- #
    # TRT01A fallback: subjects never dosed take planned treatment
    TRT01A = if_else(is.na(TRT01A), TRT01P, TRT01A)
  ) |>
  select(STUDYID, USUBJID, SUBJID, SITEID, INVID, COUNTRY, AGE, AGEU, AGEGR1, AGEGR1N, SEX, SEXN, RACE, RACEN, ETHNIC, RACEOTH, BMIBL, BMIBLGR1, HEIGHTBL, WEIGHTBL, ARM, ARMCD, ACTARM, ACTARMCD, TRT01P, TRT01PN, TRT01A, TRT01AN, TRTSDT, TRTSDTM, TRTEDT, TRTDURD, TRTEPSDT, TRTEPEDT, EOSSTT, EOSDT, DCSREAS, DCSREASP, DCTDT, COMPFL, DTHFL, DTHDTC, DTHDT, SAFFL, ITTFL, PPROTFL, ENRLFL, RANDFL, RFICDTC, RFICDT, RANDDT, SCRFREAS, CMFL, CMINFL, MHFL, DURDISM, DURDSGR1, SCRPDT, FUPDT, RANDDY, DTHDY, EOSDY, EPOCHFL)