/**********************************/
/* Program: adsl.sas              */
/* Generated by sas-program-generator */
/**********************************/

/* Pre-step: summarize EX to one row per subject */
proc sql;
  create table ex_summary as select
    usubjid,
    min(case when exdose > 0 and exstdtc ne '' 
        then datepart(input(exstdtc, e8601dt.)) end) as TRTSDT format=date9.,
    max(case when exdose > 0 and exendtc ne '' 
        then datepart(input(exendtc, e8601dt.)) end) as TRTEDT format=date9.
  from ex
  group by usubjid;
quit;

data adsl;
  merge dm ex_summary;
  by usubjid;

/* Derive AGEGR1: Pooled Age Group 1 */
length AGEGR1 $10;
label AGEGR1 = "Pooled Age Group 1";

select;
  when (AGE < 65) AGEGR1 = "<65";
  when (65 <= AGE <= 80) AGEGR1 = "65-80";
  when (AGE > 80) AGEGR1 = ">80";
  otherwise AGEGR1 = "";
end;

/* Derive AGEGR1N: Numeric code for AGEGR1 */
length AGEGR1N 8;
label AGEGR1N = "Pooled Age Group 1 (N)";

select (AGEGR1);
  when ("<65") AGEGR1N = 1;
  when ("65-80") AGEGR1N = 2;
  when (">80") AGEGR1N = 3;
  otherwise AGEGR1N = .;
end;

/* TRT01P: Planned Treatment for Period 01 - Set to DM.ARM */
length TRT01P $40;
label TRT01P = "Planned Treatment for Period 01";
TRT01P = ARM;

/* TRT01PN: Planned Treatment for Period 01 (N) */
length TRT01PN 8;
label TRT01PN = "Planned Treatment for Period 01 (N)";

select (TRT01P);
  when ("Placebo") TRT01PN = 0;
  when ("Drug A 50mg") TRT01PN = 1;
  when ("Drug A 100mg") TRT01PN = 2;
  otherwise TRT01PN = .;
end;

/* TRTDURD: Total Treatment Duration (Days) */
/* Derivation: TRTEDT - TRTSDT + 1. Missing if either date is missing. */
length TRTDURD 8;
label TRTDURD = "Total Treatment Duration (Days)";
if not missing(TRTEDT) and not missing(TRTSDT) then TRTDURD = TRTEDT - TRTSDT + 1;
else TRTDURD = .;

/* SAFFL: Y if TRTSDT is non-missing; else N */
length SAFFL $1;
label SAFFL = "Safety Population Flag";
if not missing(TRTSDT) then SAFFL = "Y";
else SAFFL = "N";

/* ITTFL: Y if ARM is not missing and not "Screen Failure"; else N */
length ITTFL $1;
label ITTFL = "Intent-To-Treat Population Flag";

if not missing(ARM) and upcase(ARM) ne "SCREEN FAILURE" then ITTFL = "Y";
else ITTFL = "N";

  keep STUDYID USUBJID SUBJID SITEID AGE AGEU AGEGR1 AGEGR1N SEX RACE ARM TRT01P TRT01PN TRT01A TRTSDT TRTEDT TRTDURD SAFFL ITTFL DTHFL;
run;