/**********************************/
/* Program: adsl.sas              */
/* Generated by sas-program-generator */
/**********************************/

/* Pre-step 1: dosing records, earliest first */
proc sort data=ex(where=(exdose > 0 and exstdtc ne '')) out=ex_dosed;
  by usubjid exstdtc;
run;

/* Pre-step 2: treatment from the first dosing record */
data ex_first(keep=usubjid TRT01A);
  set ex_dosed;
  by usubjid exstdtc;
  if first.usubjid;
  length TRT01A $40;
  TRT01A = extrt;
run;

/* Pre-step 3: first and last dosing dates per subject */
proc sql;
  create table ex_dates as select
    usubjid,
    min(input(substr(exstdtc,1,10), ?? e8601da.)) as TRTSDT  format=date9.,
    min(input(exstdtc, ?? e8601dt.))             as TRTSDTM format=datetime19.,
    max(input(substr(exendtc,1,10), ?? e8601da.)) as TRTEDT  format=date9.
  from ex
  where exdose > 0
  group by usubjid;
quit;

/* Pre-step 4: transpose SUPPDM (tall) to one row per subject (wide) */
proc sort data=suppdm out=suppdm_s;
  by usubjid qnam;
run;

proc transpose data=suppdm_s out=suppdm_w(drop=_name_);
  by usubjid;
  id qnam;
  var qval;
run;

/* Pre-step 5: treatment epoch dates from SE (ETCD = TRT) */
proc sort data=se(where=(etcd = 'TRT')) out=se_trt;
  by usubjid sestdtc;
run;

data se_epoch(keep=usubjid TRTEPSDT TRTEPEDT);
  set se_trt;
  by usubjid sestdtc;
  if first.usubjid;
  TRTEPSDT = input(substr(sestdtc,1,10), ?? yymmdd10.);
  TRTEPEDT = input(substr(seendtc,1,10), ?? yymmdd10.);
  format TRTEPSDT TRTEPEDT date9.;
run;

/* Pre-step 6: end-of-study disposition (DS) */
proc sort data=ds(where=(dscat='DISPOSITION EVENT' and missing(dsscat))) out=ds_eos;
  by usubjid dsstdtc;
run;

data ds_summary(keep=usubjid EOSSTT EOSDT DCSREAS DCSREASP);
  set ds_eos;
  by usubjid dsstdtc;
  if first.usubjid;
  length EOSSTT $20 DCSREAS $40 DCSREASP $200;
  if dsdecod = 'COMPLETED' then EOSSTT = 'COMPLETED';
  else EOSSTT = 'DISCONTINUED';
  EOSDT = input(substr(dsstdtc,1,10), ?? yymmdd10.);
  if EOSSTT = 'DISCONTINUED' then do;
    DCSREAS = dsdecod;
    DCSREASP = dsterm;
  end;
  format EOSDT date9.;
run;

/* Pre-step 7: treatment discontinuation date (DS, DSSCAT='STUDY TREATMENT') */
proc sort data=ds(where=(dscat='DISPOSITION EVENT' and dsscat='STUDY TREATMENT' and dsdecod ne 'COMPLETED')) out=ds_trt;
  by usubjid dsstdtc;
run;

data ds_trtdisc(keep=usubjid DCTDT);
  set ds_trt;
  by usubjid dsstdtc;
  if first.usubjid;
  DCTDT = input(substr(dsstdtc,1,10), ?? yymmdd10.);
  format DCTDT date9.;
run;

/* Pre-step 8: baseline vitals from VS (VSBLFL='Y') */
proc sql;
  create table vs_summary as select
    usubjid,
    max(case when vstestcd = 'BMI'    and vsblfl = 'Y' then vsstresn end) as BMIBL    format=8.1,
    max(case when vstestcd = 'HEIGHT' and vsblfl = 'Y' then vsstresn end) as HEIGHTBL format=8.1,
    max(case when vstestcd = 'WEIGHT' and vsblfl = 'Y' then vsstresn end) as WEIGHTBL format=8.1
  from vs
  group by usubjid;
quit;

/* Pre-step 9: CM existence flags */
proc sql;
  create table cm_summary as select
    usubjid,
    case when sum(cmcat in ('PRIOR','CONCOMITANT')) > 0 then 'Y' else 'N' end as CMFL   length=1,
    case when sum(cmcat = 'PRIOR')                > 0 then 'Y' else 'N' end as CMINFL length=1
  from cm
  group by usubjid;
quit;

/* Pre-step 10: MH existence flag */
proc sql;
  create table mh_summary as select
    usubjid,
    case when sum(mhcat = 'PRIMARY DIAGNOSIS' and mhenrf = 'ONGOING') > 0
         then 'Y' else 'N' end as MHFL length=1
  from mh
  group by usubjid;
quit;

data adsl;
  merge dm ex_dates ex_first suppdm_w se_epoch ds_summary ds_trtdisc vs_summary cm_summary mh_summary;
  by usubjid;

* Derive AGEGR1 per specification;
length AGEGR1 $10;
label AGEGR1 = "Pooled Age Group 1";
if AGE < 65 then AGEGR1 = "<65";
else if AGE <= 80 then AGEGR1 = "65-80";
else if AGE > 80 then AGEGR1 = ">80";

/* Derive AGEGR1N from AGEGR1 */
length AGEGR1N 8;
label AGEGR1N = 'Pooled Age Group 1 (N)';
if AGEGR1 = "<65" then AGEGR1N = 1;
else if AGEGR1 = "65-80" then AGEGR1N = 2;
else if AGEGR1 = ">80" then AGEGR1N = 3;

/* SEXN: Sex (N) */
length SEXN 8;
label SEXN = "Sex (N)";
if SEX = "M" then SEXN = 1;
else if SEX = "F" then SEXN = 2;

/* RACEN: Race (N) */
length RACEN 8;
label RACEN = "Race (N)";

if RACE = "WHITE" then RACEN = 1;
else if RACE = "BLACK OR AFRICAN AMERICAN" then RACEN = 2;
else if RACE = "ASIAN" then RACEN = 3;
else if RACE = "AMERICAN INDIAN OR ALASKA NATIVE" then RACEN = 4;
else if RACE = "OTHER" then RACEN = 5;

/* BMIBLGR1: Baseline BMI Group */
length BMIBLGR1 $20;
label BMIBLGR1 = "Baseline BMI Group";
if not missing(BMIBL) then do;
    if BMIBL < 25 then BMIBLGR1 = "<25";
    else if BMIBL < 30 then BMIBLGR1 = "25-<30";
    else BMIBLGR1 = ">=30";
end;

/* TRT01P: Planned Treatment for Period 01 */
length TRT01P $40;
label TRT01P = "Planned Treatment for Period 01";
TRT01P = ARM;

* Derive TRT01PN from TRT01P per specification;
length TRT01PN 8;
label TRT01PN = "Planned Treatment for Period 01 (N)";
select(TRT01P);
    when("Placebo") TRT01PN = 0;
    when("Drug A 50mg") TRT01PN = 1;
    when("Drug A 100mg") TRT01PN = 2;
    otherwise TRT01PN = .;
end;

* Derive TRT01AN: Actual Treatment for Period 01 (N);
length TRT01AN 8;
label TRT01AN = "Actual Treatment for Period 01 (N)";
select (TRT01A);
    when ("Placebo") TRT01AN = 0;
    when ("Drug A 50mg") TRT01AN = 1;
    when ("Drug A 100mg") TRT01AN = 2;
    otherwise TRT01AN = .;
end;

/* TRTDURD: Total Treatment Duration (Days) */
length TRTDURD 8;
label TRTDURD = "Total Treatment Duration (Days)";
if not missing(TRTEDT) and not missing(TRTSDT) then TRTDURD = TRTEDT - TRTSDT + 1;
else call missing(TRTDURD);

* Derive study completion flag based on end of study status;
length COMPFL $1;
label COMPFL = 'Study Completion Flag';
if EOSSTT = "COMPLETED" then COMPFL = 'Y';
else COMPFL = 'N';

/* QC FLAG: FAIL: Invalid informat syntax '?? E8601DA.' - should be 'E8601DA.' or 'yymmdd10.' */
/* Derive DTHDT from DTHDTC per specification */
length DTHDT 8;
label DTHDT = "Date of Death";
format DTHDT DATE9.;
if missing(DTHDTC) or length(DTHDTC) < 10 then DTHDT = .;
else DTHDT = input(DTHDTC, ?? E8601DA.);

/* SAFFL: Safety Population Flag - Y if TRTSDT is non-missing, otherwise N */
length SAFFL $1;
label SAFFL = "Safety Population Flag";
if not missing(TRTSDT) then SAFFL = 'Y';
else SAFFL = 'N';

* Derive Intent-To-Treat Population Flag;
length ITTFL $1;
label ITTFL = "Intent-To-Treat Population Flag";
if not missing(ARM) and ARM ne "Screen Failure" then ITTFL = 'Y';
else ITTFL = 'N';

/* PPROTFL: Per-Protocol Population Flag */
length PPROTFL $1;
label PPROTFL = "Per-Protocol Population Flag";
if ITTFL = "Y" and EOSSTT = "COMPLETED" and COMPFL = "Y" then PPROTFL = "Y";
else PPROTFL = "N";

* Derivation of Enrolled Population Flag;
length ENRLFL $1;
label ENRLFL = "Enrolled Population Flag";
if not missing(RFICDTC) then ENRLFL = 'Y';
else ENRLFL = 'N';

/* Derive Randomised Population Flag */
length RANDFL $1;
label RANDFL = 'Randomised Population Flag';
if not missing(RANDDT) then RANDFL = 'Y';
else RANDFL = 'N';

/* RFICDT: Date of Informed Consent */
length RFICDT 8;
label RFICDT = "Date of Informed Consent";
if missing(RFICDTC) or length(RFICDTC) < 10 then call missing(RFICDT);
else RFICDT = input(RFICDTC, ??E8601DA.);

/* Derive Duration of Disease Group */
length DURDSGR1 $20;
label DURDSGR1 = "Duration of Disease Group";
if DURDISM < 12 then DURDSGR1 = "<1 year";
else if 12 <= DURDISM < 36 then DURDSGR1 = "1-<3 years";
else if DURDISM >= 36 then DURDSGR1 = ">=3 years";

/* Derive Day of Randomisation Relative to Screening per CDISC --DY convention */
length RANDDY 8;
label RANDDY = "Day of Randomisation Relative to Screening";

if missing(RANDDT) or missing(SCRPDT) then call missing(RANDDY);
else RANDDY = (RANDDT - SCRPDT) + (RANDDT >= SCRPDT);

/* DTHDY: Day of Death Relative to First Dose */
length DTHDY 8;
label DTHDY = "Day of Death Relative to First Dose";
if missing(DTHDT) or missing(TRTSDT) then call missing(DTHDY);
else DTHDY = (DTHDT - TRTSDT) + (DTHDT >= TRTSDT);

/* Derive EOSDY per CDISC --DY convention */
length EOSDY 8;
label EOSDY = 'Day of End of Study Relative to First Dose';
if missing(EOSDT) or missing(TRTSDT) then EOSDY = .;
else if EOSDT >= TRTSDT then EOSDY = (EOSDT - TRTSDT) + 1;
else EOSDY = EOSDT - TRTSDT;

/* EPOCHFL: Entered Treatment Epoch Flag */
length EPOCHFL $1;
label EPOCHFL = 'Entered Treatment Epoch Flag';
if not missing(TRTEPSDT) then EPOCHFL = 'Y';
else EPOCHFL = 'N';

/* TRT01A fallback: subjects never dosed take planned treatment */
if missing(TRT01A) then TRT01A = TRT01P;

  keep STUDYID USUBJID SUBJID SITEID INVID COUNTRY AGE AGEU AGEGR1 AGEGR1N SEX SEXN RACE RACEN ETHNIC RACEOTH BMIBL BMIBLGR1 HEIGHTBL WEIGHTBL ARM ARMCD ACTARM ACTARMCD TRT01P TRT01PN TRT01A TRT01AN TRTSDT TRTSDTM TRTEDT TRTDURD TRTEPSDT TRTEPEDT EOSSTT EOSDT DCSREAS DCSREASP DCTDT COMPFL DTHFL DTHDTC DTHDT SAFFL ITTFL PPROTFL ENRLFL RANDFL RFICDTC RFICDT RANDDT SCRFREAS CMFL CMINFL MHFL DURDISM DURDSGR1 SCRPDT FUPDT RANDDY DTHDY EOSDY EPOCHFL;
run;