from generator import generate_sas
from prompt_builder import build_prompt
from reviewer import review_block
from improver import improve_block

def clean(code):
    """Remove markdown fences if the model added them anyway."""
    return code.replace("```sas", "").replace("```", "").strip()

def known_variables(spec):
    """All variables legitimately available inside the main data step."""
    # variables the spec defines
    spec_vars = list(spec["Variable"])
    # SDTM columns arriving from DM
    dm_vars = ["STUDYID", "USUBJID", "SUBJID", "SITEID", "AGE", "AGEU",
               "SEX", "RACE", "ARM", "ARMCD", "ACTARM", "DTHFL", "RFSTDTC", "RFENDTC"]
    # columns created by the pre-steps
    prestep_vars = ["TRTSDT", "TRTEDT", "TRT01A", "TRTEPSDT", "TRTEPEDT",
                    "RACEOTH", "COMPLT"]
    return sorted(set(spec_vars + dm_vars + prestep_vars))

def gen_block(row):
    """Generate one variable's derivation logic via the model."""
    print("Generating:", row["Variable"])
    return clean(generate_sas(build_prompt(row)))

def assemble_adsl(spec, derived, ex_summary, main_step):
    parts = []

    # ---- Header
    parts.append("/**********************************/")
    parts.append("/* Program: adsl.sas              */")
    parts.append("/* Generated by sas-program-generator */")
    parts.append("/**********************************/")
    parts.append("")

    # ---- Pre-step 1: dosing records only, sorted by date
    parts.append("/* Pre-step 1: dosing records, earliest first */")
    parts.append("proc sort data=ex(where=(exdose > 0 and exstdtc ne '')) out=ex_dosed;")
    parts.append("  by usubjid exstdtc;")
    parts.append("run;")
    parts.append("")

    # ---- Pre-step 2: first treatment per subject
    parts.append("/* Pre-step 2: treatment from the first dosing record */")
    parts.append("data ex_first(keep=usubjid TRT01A);")
    parts.append("  set ex_dosed;")
    parts.append("  by usubjid exstdtc;")
    parts.append("  if first.usubjid;")
    parts.append("  length TRT01A $40;")
    parts.append("  TRT01A = extrt;")
    parts.append("run;")
    parts.append("")

    # ---- Pre-step 3: treatment date span per subject
    parts.append("/* Pre-step 3: first and last dosing dates per subject */")
    parts.append("proc sql;")
    parts.append("  create table ex_dates as select")
    parts.append("    usubjid,")
    parts.append("    min(input(substr(exstdtc,1,10), ?? yymmdd10.)) as TRTSDT format=date9.,")
    parts.append("    max(input(substr(exendtc,1,10), ?? yymmdd10.)) as TRTEDT format=date9.")
    parts.append("  from ex")
    parts.append("  where exdose > 0")
    parts.append("  group by usubjid;")
    parts.append("quit;")
    parts.append("")

    # ---- Pre-step 4: transpose SUPPDM to one row per subject
    parts.append("/* Pre-step 4: transpose SUPPDM (tall) to one row per subject (wide) */")
    parts.append("proc sort data=suppdm out=suppdm_s;")
    parts.append("  by usubjid qnam;")
    parts.append("run;")
    parts.append("")
    parts.append("proc transpose data=suppdm_s out=suppdm_w(drop=_name_);")
    parts.append("  by usubjid;")
    parts.append("  id qnam;")
    parts.append("  var qval;")
    parts.append("run;")
    parts.append("")

    # ---- Pre-step 5: treatment epoch dates from SE
    parts.append("/* Pre-step 5: treatment epoch dates from SE (ETCD = TRT) */")
    parts.append("proc sort data=se(where=(etcd = 'TRT')) out=se_trt;")
    parts.append("  by usubjid sestdtc;")
    parts.append("run;")
    parts.append("")
    parts.append("data se_epoch(keep=usubjid TRTEPSDT TRTEPEDT);")
    parts.append("  set se_trt;")
    parts.append("  by usubjid sestdtc;")
    parts.append("  if first.usubjid;")
    parts.append("  TRTEPSDT = input(substr(sestdtc,1,10), ?? yymmdd10.);")
    parts.append("  TRTEPEDT = input(substr(seendtc,1,10), ?? yymmdd10.);")
    parts.append("  format TRTEPSDT TRTEPEDT date9.;")
    parts.append("run;")
    parts.append("")

    # ---- Main step
    parts.append("data adsl;")
    parts.append("  merge dm ex_dates ex_first suppdm_w se_epoch;")
    parts.append("  by usubjid;")
    parts.append("")

   # main-step derived variables, in spec Order
    available = known_variables(spec)
    for i, row in main_step.sort_values("Order").iterrows():
        block = gen_block(row)
        print("   Improving:", row["Variable"])
        block = clean(improve_block(block, row, available))
        verdict = review_block(block, available)
        if verdict.startswith("FAIL"):
            print("   QC:", verdict)
            block = "/* QC FLAG: " + verdict + " */\n" + block
        parts.append(block)
        parts.append("")

    # TRT01A fallback: if never dosed, use planned treatment
    parts.append("/* TRT01A fallback: subjects never dosed take planned treatment */")
    parts.append("if missing(TRT01A) then TRT01A = TRT01P;")
    parts.append("")

    # keep only spec variables
    keep_list = " ".join(spec["Variable"])
    parts.append("  keep " + keep_list + ";")
    parts.append("run;")

    return "\n".join(parts)