from generator import generate_code
from prompt_builder import build_prompt
from reviewer import review_block
from improver import improve_block
from macro_lookup import load_catalog, find_macro, find_by_pattern
import config

catalog = load_catalog()
# Variables derived as side effects of another variable's macro call
# e.g. %adsl_agegr derives both AGEGR1 and AGEGR1N in one call
# e.g. %adsl_trtvar derives both TRT01P and TRT01PN in one call
MACRO_SIDE_EFFECTS = {"AGEGR1N", "TRT01PN"}


def clean(code):
    """Remove markdown fences (sas or r) if the model added them anyway."""
    for fence in ("```sas", "```r", "```R", "```"):
        code = code.replace(fence, "")
    return code.strip()


def known_variables(spec):
    """All variables legitimately available inside the main step (language-agnostic)."""
    spec_vars = list(spec["Variable"])
    dm_vars = ["STUDYID", "USUBJID", "SUBJID", "SITEID", "AGE", "AGEU",
               "SEX", "RACE", "ARM", "ARMCD", "ACTARM", "DTHFL", "RFSTDTC", "RFENDTC"]
    prestep_vars = ["TRTSDT", "TRTEDT", "TRT01A", "TRTEPSDT", "TRTEPEDT",
                    "RACEOTH", "COMPLT"]
    return sorted(set(spec_vars + dm_vars + prestep_vars))


def gen_block(row, skip_macro=False, language=None, writer_mode=None):
    """Generate one variable's derivation logic via the model."""
    print("Generating:", row["Variable"])
    return clean(generate_code(build_prompt(row, skip_macro=skip_macro, language=language), mode=writer_mode))


# ---------------------------------------------------------------------------
# Top-level: pick the language path
#
# writer_mode/reviewer_mode: explicit "local"|"api" overrides (e.g. the app's
# Mode switcher — Offline/Hybrid/API map to a (writer_mode, reviewer_mode)
# pair). None falls back to config.WRITER/config.REVIEWER, same as today.
# ---------------------------------------------------------------------------

def assemble_adsl(spec, derived, ex_summary, main_step, language=None, writer_mode=None,
                  reviewer_mode=None, cancel_event=None, use_macros=True):
    """cancel_event: optional threading.Event — checked once per variable in the
    main-step loop so a slow ADSL run (up to 3 model calls per variable) can be
    aborted between variables. The partial program returned on abort keeps
    whatever variables finished; unfinished ones are simply absent from the
    output (the trailing keep/select list still names every spec variable, so
    a partial program won't run as-is in SAS/R — that's expected, matching how
    a partial SDTM abort leaves some domains unfinished too).

    use_macros: when False, skip the validated company macro catalog
    (macro_lookup.py/macro_catalog.csv) entirely — every variable goes
    through Writer/Improver/Reviewer even where an exact catalog match
    exists, instead of using the macro call directly. For a study whose
    macros haven't been validated yet, or where custom (non-macro) logic is
    wanted. Only affects the SAS path — the catalog only has SAS macros
    today, so R generation already always goes through Writer/Improver/
    Reviewer regardless of this flag."""
    language = (language or config.LANGUAGE).lower()
    if language == "sas":
        return _assemble_adsl_sas(spec, derived, ex_summary, main_step, writer_mode, reviewer_mode,
                                  cancel_event, use_macros)
    elif language == "r":
        return _assemble_adsl_r(spec, derived, ex_summary, main_step, writer_mode, reviewer_mode, cancel_event)
    else:
        raise ValueError(f"Unknown language: {language!r} (expected 'sas' or 'r')")


# ===========================================================================
# SAS PATH — unchanged from the original assemble_adsl
# ===========================================================================

def _assemble_adsl_sas(spec, derived, ex_summary, main_step, writer_mode=None, reviewer_mode=None,
                       cancel_event=None, use_macros=True):
    parts = []

    # ---- Header
    parts.append("/**********************************/")
    parts.append("/* Program: adsl.sas              */")
    parts.append("/* Generated by sas-program-generator */")
    parts.append("/**********************************/")
    parts.append("")

    # ---- Pre-step 1: dosing records only, sorted by date
    parts.append("/* Pre-step 1: dosing records, earliest first */")
    parts.append("proc sort data=ex(where=(exdose > 0 and exstdtc ne '')) out=ex_dosed;")
    parts.append("  by usubjid exstdtc;")
    parts.append("run;")
    parts.append("")

    # ---- Pre-step 2: first treatment per subject
    parts.append("/* Pre-step 2: treatment from the first dosing record */")
    parts.append("data ex_first(keep=usubjid TRT01A);")
    parts.append("  set ex_dosed;")
    parts.append("  by usubjid exstdtc;")
    parts.append("  if first.usubjid;")
    parts.append("  length TRT01A $40;")
    parts.append("  TRT01A = extrt;")
    parts.append("run;")
    parts.append("")

    # ---- Pre-step 3: treatment date span per subject
    parts.append("/* Pre-step 3: first and last dosing dates per subject */")
    parts.append("proc sql;")
    parts.append("  create table ex_dates as select")
    parts.append("    usubjid,")
    parts.append("    min(input(substr(exstdtc,1,10), ?? e8601da.)) as TRTSDT  format=date9.,")
    parts.append("    min(input(exstdtc, ?? e8601dt.))             as TRTSDTM format=datetime19.,")
    parts.append("    max(input(substr(exendtc,1,10), ?? e8601da.)) as TRTEDT  format=date9.")
    parts.append("  from ex")
    parts.append("  where exdose > 0")
    parts.append("  group by usubjid;")
    parts.append("quit;")
    parts.append("")

    # ---- Pre-step 4: transpose SUPPDM to one row per subject
    parts.append("/* Pre-step 4: transpose SUPPDM (tall) to one row per subject (wide) */")
    parts.append("proc sort data=suppdm out=suppdm_s;")
    parts.append("  by usubjid qnam;")
    parts.append("run;")
    parts.append("")
    parts.append("proc transpose data=suppdm_s out=suppdm_w(drop=_name_);")
    parts.append("  by usubjid;")
    parts.append("  id qnam;")
    parts.append("  var qval;")
    parts.append("run;")
    parts.append("")

    # ---- Pre-step 5: treatment epoch dates from SE
    parts.append("/* Pre-step 5: treatment epoch dates from SE (ETCD = TRT) */")
    parts.append("proc sort data=se(where=(etcd = 'TRT')) out=se_trt;")
    parts.append("  by usubjid sestdtc;")
    parts.append("run;")
    parts.append("")
    parts.append("data se_epoch(keep=usubjid TRTEPSDT TRTEPEDT);")
    parts.append("  set se_trt;")
    parts.append("  by usubjid sestdtc;")
    parts.append("  if first.usubjid;")
    parts.append("  TRTEPSDT = input(substr(sestdtc,1,10), ?? yymmdd10.);")
    parts.append("  TRTEPEDT = input(substr(seendtc,1,10), ?? yymmdd10.);")
    parts.append("  format TRTEPSDT TRTEPEDT date9.;")
    parts.append("run;")
    parts.append("")

    # ---- Pre-step 6: end-of-study disposition from DS
    parts.append("/* Pre-step 6: end-of-study disposition (DS) */")
    parts.append("proc sort data=ds(where=(dscat='DISPOSITION EVENT' and missing(dsscat))) out=ds_eos;")
    parts.append("  by usubjid dsstdtc;")
    parts.append("run;")
    parts.append("")
    parts.append("data ds_summary(keep=usubjid EOSSTT EOSDT DCSREAS DCSREASP);")
    parts.append("  set ds_eos;")
    parts.append("  by usubjid dsstdtc;")
    parts.append("  if first.usubjid;")
    parts.append("  length EOSSTT $20 DCSREAS $40 DCSREASP $200;")
    parts.append("  if dsdecod = 'COMPLETED' then EOSSTT = 'COMPLETED';")
    parts.append("  else EOSSTT = 'DISCONTINUED';")
    parts.append("  EOSDT = input(substr(dsstdtc,1,10), ?? yymmdd10.);")
    parts.append("  if EOSSTT = 'DISCONTINUED' then do;")
    parts.append("    DCSREAS = dsdecod;")
    parts.append("    DCSREASP = dsterm;")
    parts.append("  end;")
    parts.append("  format EOSDT date9.;")
    parts.append("run;")
    parts.append("")

    # ---- Pre-step 7: treatment discontinuation date from DS
    parts.append("/* Pre-step 7: treatment discontinuation date (DS, DSSCAT='STUDY TREATMENT') */")
    parts.append("proc sort data=ds(where=(dscat='DISPOSITION EVENT' and dsscat='STUDY TREATMENT' and dsdecod ne 'COMPLETED')) out=ds_trt;")
    parts.append("  by usubjid dsstdtc;")
    parts.append("run;")
    parts.append("")
    parts.append("data ds_trtdisc(keep=usubjid DCTDT);")
    parts.append("  set ds_trt;")
    parts.append("  by usubjid dsstdtc;")
    parts.append("  if first.usubjid;")
    parts.append("  DCTDT = input(substr(dsstdtc,1,10), ?? yymmdd10.);")
    parts.append("  format DCTDT date9.;")
    parts.append("run;")
    parts.append("")

    # ---- Pre-step 8: baseline vitals from VS
    parts.append("/* Pre-step 8: baseline vitals from VS (VSBLFL='Y') */")
    parts.append("proc sql;")
    parts.append("  create table vs_summary as select")
    parts.append("    usubjid,")
    parts.append("    max(case when vstestcd = 'BMI'    and vsblfl = 'Y' then vsstresn end) as BMIBL    format=8.1,")
    parts.append("    max(case when vstestcd = 'HEIGHT' and vsblfl = 'Y' then vsstresn end) as HEIGHTBL format=8.1,")
    parts.append("    max(case when vstestcd = 'WEIGHT' and vsblfl = 'Y' then vsstresn end) as WEIGHTBL format=8.1")
    parts.append("  from vs")
    parts.append("  group by usubjid;")
    parts.append("quit;")
    parts.append("")

    # ---- Pre-step 9: prior/concomitant medication flags from CM
    parts.append("/* Pre-step 9: CM existence flags */")
    parts.append("proc sql;")
    parts.append("  create table cm_summary as select")
    parts.append("    usubjid,")
    parts.append("    case when sum(cmcat in ('PRIOR','CONCOMITANT')) > 0 then 'Y' else 'N' end as CMFL   length=1,")
    parts.append("    case when sum(cmcat = 'PRIOR')                > 0 then 'Y' else 'N' end as CMINFL length=1")
    parts.append("  from cm")
    parts.append("  group by usubjid;")
    parts.append("quit;")
    parts.append("")

    # ---- Pre-step 10: medical history flag from MH
    parts.append("/* Pre-step 10: MH existence flag */")
    parts.append("proc sql;")
    parts.append("  create table mh_summary as select")
    parts.append("    usubjid,")
    parts.append("    case when sum(mhcat = 'PRIMARY DIAGNOSIS' and mhenrf = 'ONGOING') > 0")
    parts.append("         then 'Y' else 'N' end as MHFL length=1")
    parts.append("  from mh")
    parts.append("  group by usubjid;")
    parts.append("quit;")
    parts.append("")

    # ---- Main step
    parts.append("data adsl;")
    parts.append("  merge dm ex_dates ex_first suppdm_w se_epoch ds_summary ds_trtdisc vs_summary cm_summary mh_summary;")
    parts.append("  by usubjid;")
    parts.append("")

    # main-step derived variables, in spec Order
    available = known_variables(spec)
    for i, row in main_step.sort_values("Order").iterrows():
        if cancel_event is not None and cancel_event.is_set():
            parts.append(f"/* -- generation aborted by user before variable {row['Variable']} -- */")
            break
        # Skip variables already derived as macro side effects — but only
        # when macros are actually in use; with use_macros=False nothing
        # produces AGEGR1N/TRT01PN as a side effect anymore, so skipping them
        # here would drop them from the output entirely instead of routing
        # them through Writer/Improver/Reviewer like any other variable.
        if use_macros and row["Variable"] in MACRO_SIDE_EFFECTS:
            print("Side effect (skipped):", row["Variable"])
            continue

        var = row["Variable"]

        # 1. Exact catalog match — use macro call directly
        match = find_macro(var, catalog) if use_macros else None
        if match:
            print("Macro match:", var, "->", match["macro"])
            block = f"/*-- BEGIN {var} --*/\n/* {var}: using validated macro */\n{match['call']}\n/*-- END {var} --*/"
        else:
            # 2. Pattern match + generate (Writer only — Improve/Review are
            # separate on-demand actions per variable now, see
            # app.py's improve_adsl_block/review_adsl_block, so a fresh
            # Generate isn't paying for 2 extra sequential model calls per
            # variable it may not want)
            pmatch = find_by_pattern(var, str(row["Derivation"]), catalog) if use_macros else None
            block = clean(gen_block(row, language="sas", writer_mode=writer_mode))
            if pmatch:
                print("   Pattern hint:", var, "->", pmatch["pattern"])
                block = pmatch["suggested_call"] + "\n" + block
            block = f"/*-- BEGIN {var} --*/\n{block}\n/*-- END {var} --*/"

        parts.append(block)
        parts.append("")

    # TRT01A fallback: if never dosed, use planned treatment
    parts.append("/* TRT01A fallback: subjects never dosed take planned treatment */")
    parts.append("if missing(TRT01A) then TRT01A = TRT01P;")
    parts.append("")

    # keep only spec variables
    keep_list = " ".join(spec["Variable"])
    parts.append("  keep " + keep_list + ";")
    parts.append("run;")

    return "\n".join(parts)


# ===========================================================================
# R PATH — plain tidyverse; mirrors the SAS ADSL stage for stage
# ===========================================================================

def _r_add_comma(line):
    """Append the mutate() separator comma to a line of R, placing it BEFORE any
    inline `#` comment (R would otherwise treat the comma as part of the comment
    and swallow it). Quotes are respected so a `#` inside a string is ignored.
    """
    in_s = None  # current string delimiter, or None
    hash_pos = None
    for i, ch in enumerate(line):
        if in_s:
            if ch == in_s:
                in_s = None
        elif ch in ("'", '"'):
            in_s = ch
        elif ch == "#":
            hash_pos = i
            break
    if hash_pos is None:
        return line.rstrip() + ","
    code, comment = line[:hash_pos], line[hash_pos:]
    return code.rstrip() + ",  " + comment.rstrip()


def _adsl_presteps_r():
    """The 10 ADSL pre-steps ported to dplyr. Each mirrors its SAS pre-step.

    Note vs SAS: SAS 'if first.usubjid' relies on the preceding proc sort, so
    in R every 'take the first per subject' does an explicit arrange() before
    slice(1) — R does not inherit sort order. Dates: SAS e8601da./yymmdd10.
    both become as.Date(substr(x,1,10)); the datetime (e8601dt.) becomes
    as.POSIXct.
    """
    return r'''# Pre-step 1: dosing records, earliest first
ex_dosed <- ex |>
  filter(EXDOSE > 0, EXSTDTC != "") |>
  arrange(USUBJID, EXSTDTC)

# Pre-step 2: treatment from the first dosing record
ex_first <- ex_dosed |>
  group_by(USUBJID) |>
  slice(1) |>
  ungroup() |>
  transmute(USUBJID, TRT01A = EXTRT)

# Pre-step 3: first and last dosing dates per subject
ex_dates <- ex |>
  filter(EXDOSE > 0) |>
  group_by(USUBJID) |>
  summarise(
    TRTSDT  = min(as.Date(substr(EXSTDTC, 1, 10)), na.rm = TRUE),
    TRTSDTM = min(as.POSIXct(EXSTDTC, format = "%Y-%m-%dT%H:%M:%S", tz = "UTC"), na.rm = TRUE),
    TRTEDT  = max(as.Date(substr(EXENDTC, 1, 10)), na.rm = TRUE),
    .groups = "drop"
  )

# Pre-step 4: transpose SUPPDM (tall) to one row per subject (wide)
suppdm_w <- suppdm |>
  select(USUBJID, QNAM, QVAL) |>
  pivot_wider(names_from = QNAM, values_from = QVAL)

# Pre-step 5: treatment epoch dates from SE (ETCD = TRT)
se_epoch <- se |>
  filter(ETCD == "TRT") |>
  arrange(USUBJID, SESTDTC) |>
  group_by(USUBJID) |>
  slice(1) |>
  ungroup() |>
  transmute(
    USUBJID,
    TRTEPSDT = as.Date(substr(SESTDTC, 1, 10)),
    TRTEPEDT = as.Date(substr(SEENDTC, 1, 10))
  )

# Pre-step 6: end-of-study disposition (DS)
ds_summary <- ds |>
  filter(DSCAT == "DISPOSITION EVENT", is.na(DSSCAT) | DSSCAT == "") |>
  arrange(USUBJID, DSSTDTC) |>
  group_by(USUBJID) |>
  slice(1) |>
  ungroup() |>
  mutate(
    EOSSTT   = if_else(DSDECOD == "COMPLETED", "COMPLETED", "DISCONTINUED"),
    EOSDT    = as.Date(substr(DSSTDTC, 1, 10)),
    DCSREAS  = if_else(EOSSTT == "DISCONTINUED", DSDECOD, NA_character_),
    DCSREASP = if_else(EOSSTT == "DISCONTINUED", DSTERM,  NA_character_)
  ) |>
  select(USUBJID, EOSSTT, EOSDT, DCSREAS, DCSREASP)

# Pre-step 7: treatment discontinuation date (DS, DSSCAT='STUDY TREATMENT')
ds_trtdisc <- ds |>
  filter(DSCAT == "DISPOSITION EVENT", DSSCAT == "STUDY TREATMENT", DSDECOD != "COMPLETED") |>
  arrange(USUBJID, DSSTDTC) |>
  group_by(USUBJID) |>
  slice(1) |>
  ungroup() |>
  transmute(USUBJID, DCTDT = as.Date(substr(DSSTDTC, 1, 10)))

# Pre-step 8: baseline vitals from VS (VSBLFL='Y')
vs_summary <- vs |>
  filter(VSBLFL == "Y", VSTESTCD %in% c("BMI", "HEIGHT", "WEIGHT")) |>
  select(USUBJID, VSTESTCD, VSSTRESN) |>
  pivot_wider(names_from = VSTESTCD, values_from = VSSTRESN) |>
  rename(BMIBL = BMI, HEIGHTBL = HEIGHT, WEIGHTBL = WEIGHT)

# Pre-step 9: CM existence flags
cm_summary <- cm |>
  group_by(USUBJID) |>
  summarise(
    CMFL   = if_else(any(CMCAT %in% c("PRIOR", "CONCOMITANT")), "Y", "N"),
    CMINFL = if_else(any(CMCAT == "PRIOR"), "Y", "N"),
    .groups = "drop"
  )

# Pre-step 10: MH existence flag
mh_summary <- mh |>
  group_by(USUBJID) |>
  summarise(
    MHFL = if_else(any(MHCAT == "PRIMARY DIAGNOSIS" & MHENRF == "ONGOING"), "Y", "N"),
    .groups = "drop"
  )'''


def _assemble_adsl_r(spec, derived, ex_summary, main_step, writer_mode=None, reviewer_mode=None, cancel_event=None):
    parts = []

    # ---- Header + libraries
    parts.append("# ********************************")
    parts.append("# Program: adsl.R")
    parts.append("# Generated by SpecGen (target = r)")
    parts.append("# Plain tidyverse; same spec as adsl.sas (independent implementation)")
    parts.append("# ********************************")
    parts.append("library(dplyr)")
    parts.append("library(tidyr)")
    parts.append("")

    # ---- 10 pre-steps
    parts.append(_adsl_presteps_r())
    parts.append("")

    # ---- Main step: join all sources on USUBJID (== SAS merge by usubjid)
    parts.append("# Main step: join DM with every pre-step summary")
    parts.append("adsl <- dm |>")
    parts.append("  left_join(ex_dates,   by = \"USUBJID\") |>")
    parts.append("  left_join(ex_first,   by = \"USUBJID\") |>")
    parts.append("  left_join(suppdm_w,   by = \"USUBJID\") |>")
    parts.append("  left_join(se_epoch,   by = \"USUBJID\") |>")
    parts.append("  left_join(ds_summary, by = \"USUBJID\") |>")
    parts.append("  left_join(ds_trtdisc, by = \"USUBJID\") |>")
    parts.append("  left_join(vs_summary, by = \"USUBJID\") |>")
    parts.append("  left_join(cm_summary, by = \"USUBJID\") |>")
    parts.append("  left_join(mh_summary, by = \"USUBJID\") |>")
    parts.append("  mutate(")

    # ---- main-step derived variables, in spec Order (each an inner mutate expr)
    available = known_variables(spec)
    for i, row in main_step.sort_values("Order").iterrows():
        if cancel_event is not None and cancel_event.is_set():
            parts.append(f"    # -- generation aborted by user before variable {row['Variable']} -- #")
            break
        if row["Variable"] in MACRO_SIDE_EFFECTS:
            print("Side effect (skipped):", row["Variable"])
            continue

        var = row["Variable"]
        # No macro branch in R (SAS-only catalog). Writer only — Improve/Review
        # are separate on-demand actions per variable now (see app.py's
        # improve_adsl_block/review_adsl_block), not run automatically here.
        block = gen_block(row, language="r", writer_mode=writer_mode)

        # indent the derivation into the mutate() and wrap in R markers.
        # The mutate() argument separator MUST be a real comma on the code
        # line — a trailing "#" comment would swallow a comma placed after it,
        # so the comma goes on the last non-comment code line, before END.
        raw_lines = block.splitlines()
        indented = ["    " + ln for ln in raw_lines]
        # find the last line that is actual code (not a pure # comment) to carry
        # the mutate() separator comma
        comma_idx = None
        for i in range(len(indented) - 1, -1, -1):
            if not indented[i].lstrip().startswith("#"):
                comma_idx = i
                break
        if comma_idx is not None:
            indented[comma_idx] = _r_add_comma(indented[comma_idx])
        else:
            # Writer produced no actual code, only comments (e.g. punted on an
            # ambiguous derivation). A bare "," here would leave TWO commas in a
            # row inside mutate() (a parse/argument error) and never create the
            # {var} column, so the final select({var}) would fail with
            # "object not found". Emit a typed NA stub instead: keeps the comma
            # count correct and the column real, while making the gap visible.
            na_value = "NA_character_" if str(row["Type"]).lower() == "text" else "NA_real_"
            indented.append(f"    {var} = {na_value},  # WRITER PRODUCED NO CODE for this derivation")
        body = "\n".join(indented)
        wrapped = f"    # -- BEGIN {var} -- #\n{body}\n    # -- END {var} -- #"
        parts.append(wrapped)

    # ---- TRT01A fallback (== SAS: if missing then planned)
    parts.append("    # TRT01A fallback: subjects never dosed take planned treatment")
    parts.append("    TRT01A = if_else(is.na(TRT01A), TRT01P, TRT01A)")
    parts.append("  ) |>")

    # ---- keep only spec variables (SAS keep -> dplyr select)
    keep_list = ", ".join(spec["Variable"])
    parts.append(f"  select({keep_list})")

    return "\n".join(parts)
