from spec_differ import diff_specs
from assembler import gen_block, clean, improve_block
from reviewer import review_block
from macro_lookup import load_catalog, find_macro
from assembler import known_variables
import pandas as pd
import re
from generator import generate_api

catalog = load_catalog()

def patch_program(sas_file, spec_v1, spec_v2):
    """Patch an existing .sas program based on spec changes."""

    diff = diff_specs(spec_v1, spec_v2)

    with open(sas_file, encoding="utf-8", errors="replace") as f:
        program = f.read()

    spec = pd.read_excel(spec_v2, sheet_name="Variables")
    available = known_variables(spec)

    print(f"\nPatching {sas_file}")
    print(f"  Changed : {[c['variable'] for c in diff['changed']]}")
    print(f"  New     : {diff['new']}")
    print(f"  Deleted : {diff['deleted']}")

    # 1. Replace changed variable blocks — direct API call, no catalog anywhere
    for change in diff["changed"]:
        var = change["variable"]
        row = spec[spec["Variable"] == var]
        if row.empty:
            continue
        row = row.iloc[0]

        print(f"  Generating fresh: {var}")
        direct_prompt = f"""You are a senior clinical SAS programmer.
Write SAS 9.4 derivation logic for this ADaM variable.
Variable: {var}
Label: {row['Label']}
Type: {row['Type']}, Length: {row['Length']}
Derivation rule: {row['Derivation']}

Output ONLY the SAS code: length, label, and derivation logic.
No data/set/run statements. No explanation. No markdown fences.
One brief comment line, then the code."""

        inner = generate_api(direct_prompt).strip()
        print(f"  Generated: {inner[:100]}")
        inner = inner.replace("```sas", "").replace("```", "").strip()
        new_block = f"/*-- BEGIN {var} --*/\n{inner}\n/*-- END {var} --*/"

        pattern = rf"/\*-- BEGIN {re.escape(var)} --\*/.*?/\*-- END {re.escape(var)} --\*/"
        if re.search(pattern, program, re.DOTALL):
            program = re.sub(pattern, new_block, program, flags=re.DOTALL)
            print(f"  Replaced: {var}")
        else:
            print(f"  WARNING: no markers for {var} — appending")
            program = program.replace("  keep ", f"{new_block}\n\n  keep ")

    # 2. Remove deleted variable blocks
    for var in diff["deleted"]:
        pattern = rf"/\*-- BEGIN {re.escape(var)} --\*/.*?/\*-- END {re.escape(var)} --\*/\n?"
        program = re.sub(pattern, "", program, flags=re.DOTALL)
        print(f"  Deleted : {var}")

    # 3. Add new variable blocks before keep
    for var in diff["new"]:
        row = spec[spec["Variable"] == var]
        if row.empty:
            continue
        row = row.iloc[0]
        new_block = make_block(var, row, available)
        program = program.replace("  keep ", f"{new_block}\n\n  keep ")
        print(f"  Added   : {var}")

    # 4. Update keep list
    keep_vars = list(spec["Variable"])
    old_keep = re.search(r"  keep .*?;", program, re.DOTALL)
    if old_keep:
        new_keep = "  keep " + " ".join(keep_vars) + ";"
        program = program[:old_keep.start()] + new_keep + program[old_keep.end():]

    # 5. Update header
    if "/* Updated:" not in program:
        program = program.replace(
            "/* Generated by sas-program-generator */",
            "/* Generated by sas-program-generator */\n/* Updated: spec v2 patch */"
        )

    return program, diff


def make_block(var, row, available, force_generate=False):
    """Generate a wrapped block for one variable."""
    match = find_macro(var, catalog)
    if match and not force_generate:
        inner = f"/* {var}: using validated macro */\n{match['call']}"
    else:
        inner = clean(improve_block(gen_block(row, skip_macro=True), row, available))
    return f"/*-- BEGIN {var} --*/\n{inner}\n/*-- END {var} --*/"