from spec_differ import diff_specs
from assembler import gen_block, clean, improve_block, known_variables
from reviewer import review_block
from macro_lookup import load_catalog, find_macro, find_by_pattern
import pandas as pd
import re
from runlog import log_run
from generator import model_name
import config

catalog = load_catalog()


def _build_block(var, row, available, writer_mode=None, reviewer_mode=None, use_macros=True):
    """Generate one variable's wrapped SAS BEGIN/END block. Mirrors
    assemble_adsl's main-step loop exactly (exact catalog match used
    directly when use_macros, else Writer->Improver->Reviewer with an
    optional pattern hint) so a patched block gets the identical QC
    treatment — including the "QC FLAG" marker on FAIL — that a freshly
    generated one would. Patcher-only bug this replaced: the old "changed"
    path was a raw one-shot API call with no Improver/Reviewer step at all,
    so patched variables silently skipped QC review entirely."""
    match = find_macro(var, catalog) if use_macros else None
    if match:
        inner = f"/* {var}: using validated macro */\n{match['call']}"
        return f"/*-- BEGIN {var} --*/\n{inner}\n/*-- END {var} --*/"

    pmatch = find_by_pattern(var, str(row["Derivation"]), catalog) if use_macros else None
    block = gen_block(row, language="sas", writer_mode=writer_mode)
    block = clean(improve_block(block, row, available, language="sas", mode=reviewer_mode))
    verdict = review_block(block, available, language="sas", mode=reviewer_mode)
    if verdict.startswith("FAIL"):
        block = "/* QC FLAG: " + verdict + " */\n" + block
    if pmatch:
        block = pmatch["suggested_call"] + "\n" + block
    return f"/*-- BEGIN {var} --*/\n{block}\n/*-- END {var} --*/"


def patch_program(program, spec_v1, spec_v2, writer_mode=None, reviewer_mode=None, use_macros=True,
                  output_label="adsl.sas"):
    """Patch an ADSL SAS program (as text, not a file path — the caller
    reads/writes wherever the program actually lives, e.g. the web app's
    in-memory state rather than a stale copy on disk) based on spec changes:
    regenerate each changed variable's block, remove deleted ones, add new
    ones, then update the keep list and header. Unaffected variables are
    left byte-for-byte untouched — that's the point versus a full
    regenerate, and it's what lets the web app preserve their sign-off/
    approval status across an update instead of forcing full re-review.

    SAS only (ADSL's R path has its own mutate()-chain block format that
    this marker-based regex patching doesn't handle) — same scope as the
    macro catalog before this, not a new limitation introduced here.
    """
    diff = diff_specs(spec_v1, spec_v2)

    spec = pd.read_excel(spec_v2, sheet_name="Variables")
    available = known_variables(spec)

    print(f"\nPatching {output_label}")
    print(f"  Changed : {[c['variable'] for c in diff['changed']]}")
    print(f"  New     : {diff['new']}")
    print(f"  Deleted : {diff['deleted']}")

    # 1. Replace changed variable blocks
    for change in diff["changed"]:
        var = change["variable"]
        row = spec[spec["Variable"] == var]
        if row.empty:
            continue
        row = row.iloc[0]

        new_block = _build_block(var, row, available, writer_mode, reviewer_mode, use_macros)

        pattern = rf"/\*-- BEGIN {re.escape(var)} --\*/.*?/\*-- END {re.escape(var)} --\*/"
        if re.search(pattern, program, re.DOTALL):
            program = re.sub(pattern, new_block, program, flags=re.DOTALL)
            print(f"  Replaced: {var}")
        else:
            print(f"  WARNING: no markers for {var} — appending")
            program = program.replace("  keep ", f"{new_block}\n\n  keep ")

    # 2. Remove deleted variable blocks
    for var in diff["deleted"]:
        pattern = rf"/\*-- BEGIN {re.escape(var)} --\*/.*?/\*-- END {re.escape(var)} --\*/\n?"
        program = re.sub(pattern, "", program, flags=re.DOTALL)
        print(f"  Deleted : {var}")

    # 3. Add new variable blocks before keep
    for var in diff["new"]:
        row = spec[spec["Variable"] == var]
        if row.empty:
            continue
        row = row.iloc[0]
        new_block = _build_block(var, row, available, writer_mode, reviewer_mode, use_macros)
        program = program.replace("  keep ", f"{new_block}\n\n  keep ")
        print(f"  Added   : {var}")

    # 4. Update keep list
    keep_vars = list(spec["Variable"])
    old_keep = re.search(r"  keep .*?;", program, re.DOTALL)
    if old_keep:
        new_keep = "  keep " + " ".join(keep_vars) + ";"
        program = program[:old_keep.start()] + new_keep + program[old_keep.end():]

    # 5. Update header
    if "/* Updated:" not in program:
        program = program.replace(
            "/* Generated by sas-program-generator */",
            "/* Generated by sas-program-generator */\n/* Updated: spec v2 patch */"
        )

    # 6. Log this patch run. writer_mode/reviewer_mode fall back to
    # config.WRITER/REVIEWER (read as module attributes, not `from config
    # import ...`, for the same reason generator.py does — a plain import
    # binds the name at import time and never sees a later override) only
    # for logging when the caller didn't pass an explicit mode (e.g. the
    # test_patcher.py smoke script); the web app always passes one.
    n_touched = len(diff["changed"]) + len(diff["new"])
    eff_writer = writer_mode or config.WRITER
    eff_reviewer = reviewer_mode or config.REVIEWER
    log_run(
        spec_v2,
        f"patch/{eff_writer}-writer/{eff_reviewer}-reviewer",
        model_name(eff_writer),
        model_name(eff_reviewer),
        model_name(eff_reviewer),
        n_touched,
        output_label,
    )

    return program, diff
