/* ********************************* */
/* Program: adae_spec.sas */
/* Generated by SpecGen (adam_bds_assembler.py) */
/* ********************************* */

data adae;
    set ae;  /* raw SDTM AE domain — every ADaM-only
       variable below (PARAMCD/AVAL/BASE/..., ADSL merges, date conversions,
       analysis flags) is derived by its own spec row, not pre-built */

/*-- BEGIN ASTDT --*/
/* Derive analysis start date from AESTDTC */
length ASTDT 8;
label ASTDT = "Analysis Start Date";
ASTDT = input(substr(AESTDTC, 1, 10), E8601DA10.);
/*-- END ASTDT --*/

/*-- BEGIN AENDT --*/
* Derive analysis end date from AEENDTC;
length AENDT 8;
label AENDT = "Analysis End Date";
AENDT = input(substr(AEENDTC, 1, 10), E8601DA.);
/*-- END AENDT --*/

/*-- BEGIN AESEVN --*/
/* Derive AESEVN: Numeric severity code */
length AESEVN 8;
if upcase(AESEV)="MILD" then AESEVN=1;
else if upcase(AESEV)="MODERATE" then AESEVN=2;
else if upcase(AESEV)="SEVERE" then AESEVN=3;
label AESEVN="Severity/Intensity (N)";
/*-- END AESEVN --*/

/*-- BEGIN AERELFL --*/
/* Derive AERELFL: Relationship to Treatment Flag */
length AERELFL $1;
label AERELFL = "Relationship to Treatment Flag";
if not missing(AEREL) and AEREL ne 'NOT RELATED' then AERELFL = 'Y';
else AERELFL = 'N';
/*-- END AERELFL --*/

run;
