# ********************************
# Program: adae.R
# Generated by SpecGen (target = r)
# Events ADaM: ADAE from SDTM ae
# ********************************
library(dplyr)

# -- BEGIN ADAE_MERGE -- #
adae_adsl <- adsl |> select(USUBJID, TRTSDT, TRTEDT)

adae_merged <- ae |>
  left_join(adae_adsl, by = "USUBJID")
# -- END ADAE_MERGE -- #

# -- BEGIN ASTDT_AENDT -- #
adae_dates <- adae_merged |>
  mutate(
    ASTDT = as.Date(substr(AESTDTC, 1, 10)),
    AENDT = as.Date(substr(AEENDTC, 1, 10))
  )
# -- END ASTDT_AENDT -- #

# -- BEGIN TRTEMFL -- #
adae_flag <- adae_dates |>
  mutate(
    # On/after first dose
    TRTEMFL = if_else(
      !is.na(ASTDT) & !is.na(TRTSDT) & ASTDT >= TRTSDT,
      "Y", NA_character_
    )
  )
# -- END TRTEMFL -- #

# -- BEGIN AOCCFL -- #
adae <- adae_flag |>
  group_by(USUBJID, AEDECOD) |>
  arrange(ASTDT, .by_group = TRUE) |>
  mutate(
    # flag the first record per subject per coded term
    AOCCFL = if_else(row_number() == 1, "Y", NA_character_)
  ) |>
  ungroup()
# -- END AOCCFL -- #
