# ********************************
# Program: adcm.R
# Generated by SpecGen (target = r)
# Events ADaM: ADCM from SDTM cm
# ********************************
library(dplyr)

# -- BEGIN ADCM_MERGE -- #
adcm_adsl <- adsl |> select(USUBJID, TRTSDT, TRTEDT)

adcm_merged <- cm |>
  left_join(adcm_adsl, by = "USUBJID")
# -- END ADCM_MERGE -- #

# -- BEGIN ASTDT_AENDT -- #
adcm_dates <- adcm_merged |>
  mutate(
    ASTDT = as.Date(substr(CMSTDTC, 1, 10)),
    AENDT = as.Date(substr(CMENDTC, 1, 10))
  )
# -- END ASTDT_AENDT -- #

# -- BEGIN ONTRTFL -- #
adcm_flag <- adcm_dates |>
  mutate(
    # On/after first dose
    ONTRTFL = if_else(
      !is.na(ASTDT) & !is.na(TRTSDT) & ASTDT >= TRTSDT,
      "Y", NA_character_
    )
  )
# -- END ONTRTFL -- #

# -- BEGIN AOCCFL -- #
adcm <- adcm_flag |>
  group_by(USUBJID, CMDECOD) |>
  arrange(ASTDT, .by_group = TRUE) |>
  mutate(
    # flag the first record per subject per coded term
    AOCCFL = if_else(row_number() == 1, "Y", NA_character_)
  ) |>
  ungroup()
# -- END AOCCFL -- #
