# ********************************
# Program: adeg.R
# Generated by SpecGen (target = r)
# Findings ADaM: ADEG from SDTM eg
# ********************************
library(dplyr)

# -- BEGIN ADEG_PARAMCD -- #
adeg_paramcd <- eg |>
  mutate(
    PARAMCD = case_when(
      EGTESTCD == "HR" ~ "HR",
      EGTESTCD == "PRINTR" ~ "PRINTR",
      EGTESTCD == "QRSDUR" ~ "QRSDUR",
      EGTESTCD == "QTINT" ~ "QTINT",
      EGTESTCD == "QTCF" ~ "QTCF",
      TRUE ~ NA_character_
    ),
    PARAM = case_when(
      EGTESTCD == "HR" ~ "Heart Rate (bpm)",
      EGTESTCD == "PRINTR" ~ "PR Interval (msec)",
      EGTESTCD == "QRSDUR" ~ "QRS Duration (msec)",
      EGTESTCD == "QTINT" ~ "QT Interval (msec)",
      EGTESTCD == "QTCF" ~ "QTcF (msec)",
      TRUE ~ NA_character_
    ),
    AVAL = EGSTRESN  # standardized numeric result
  )
# -- END ADEG_PARAMCD -- #

# -- BEGIN ADEG_BASELINE -- #
adeg_baseline <- adeg_paramcd |>
  filter(VISIT == "BASELINE") |>
  group_by(USUBJID, PARAMCD) |>
  summarise(BASE = dplyr::first(AVAL), .groups = "drop")

adeg_base <- adeg_paramcd |>
  left_join(adeg_baseline, by = c("USUBJID", "PARAMCD")) |>
  mutate(
    CHG  = AVAL - BASE,
    PCHG = if_else(!is.na(BASE) & BASE != 0, 100 * (CHG / BASE), NA_real_)
  )
# -- END ADEG_BASELINE -- #

# -- BEGIN AWLO_AWHI -- #
adeg_windows <- adeg_base |>
  mutate(
    AWLO = case_when(
      VISITNUM == 1 ~ -28,
      VISITNUM == 2 ~ -14,
      VISITNUM == 4 ~ 12,
      VISITNUM == 5 ~ 26,
      VISITNUM == 6 ~ 54,
      VISITNUM == 7 ~ 82,
      VISITNUM == 8 ~ 110,
      VISITNUM == 9 ~ 166,
      VISITNUM == 10 ~ 250,
      VISITNUM == 11 ~ 362,
      VISITNUM == 12 ~ 370,
      VISITNUM == 13 ~ 377,
      VISITNUM == 14 ~ 390,
      TRUE ~ NA_real_
    ),
    AWHI = case_when(
      VISITNUM == 1 ~ -1,
      VISITNUM == 2 ~ -1,
      VISITNUM == 4 ~ 18,
      VISITNUM == 5 ~ 32,
      VISITNUM == 6 ~ 60,
      VISITNUM == 7 ~ 88,
      VISITNUM == 8 ~ 116,
      VISITNUM == 9 ~ 172,
      VISITNUM == 10 ~ 256,
      VISITNUM == 11 ~ 368,
      VISITNUM == 12 ~ 375,
      VISITNUM == 13 ~ 382,
      VISITNUM == 14 ~ 400,
      TRUE ~ NA_real_
    )
  )
# -- END AWLO_AWHI -- #

# -- BEGIN ANL01FL -- #
adeg <- adeg_windows |>
  mutate(
    # Analysis flag: within visit window and non-missing AVAL
    ANL01FL = if_else(
      !is.na(AVAL) & !is.na(AWLO) & !is.na(AWHI) &
        VISITNUM >= AWLO & VISITNUM <= AWHI,
      "Y", NA_character_
    )
  )
# -- END ANL01FL -- #
