# ********************************
# Program: adlb.R
# Generated by SpecGen (target = r)
# Findings ADaM: ADLB from SDTM lb
# ********************************
library(dplyr)

# -- BEGIN ADLB_PARAMCD -- #
adlb_paramcd <- lb |>
  mutate(
    PARAMCD = case_when(
      LBTESTCD == "GLUC" ~ "GLUC",
      LBTESTCD == "CREAT" ~ "CREAT",
      LBTESTCD == "ALT" ~ "ALT",
      LBTESTCD == "AST" ~ "AST",
      LBTESTCD == "BILI" ~ "BILI",
      LBTESTCD == "HGB" ~ "HGB",
      LBTESTCD == "WBC" ~ "WBC",
      LBTESTCD == "PLAT" ~ "PLAT",
      TRUE ~ NA_character_
    ),
    PARAM = case_when(
      LBTESTCD == "GLUC" ~ "Glucose (mmol/L)",
      LBTESTCD == "CREAT" ~ "Creatinine (umol/L)",
      LBTESTCD == "ALT" ~ "ALT (U/L)",
      LBTESTCD == "AST" ~ "AST (U/L)",
      LBTESTCD == "BILI" ~ "Total Bilirubin (umol/L)",
      LBTESTCD == "HGB" ~ "Hemoglobin (g/L)",
      LBTESTCD == "WBC" ~ "White Blood Cells (10^9/L)",
      LBTESTCD == "PLAT" ~ "Platelets (10^9/L)",
      TRUE ~ NA_character_
    ),
    AVAL = LBSTRESN  # standardized numeric result
  )
# -- END ADLB_PARAMCD -- #

# -- BEGIN ADLB_BASELINE -- #
adlb_baseline <- adlb_paramcd |>
  filter(VISIT == "BASELINE") |>
  group_by(USUBJID, PARAMCD) |>
  summarise(BASE = dplyr::first(AVAL), .groups = "drop")

adlb_base <- adlb_paramcd |>
  left_join(adlb_baseline, by = c("USUBJID", "PARAMCD")) |>
  mutate(
    CHG  = AVAL - BASE,
    PCHG = if_else(!is.na(BASE) & BASE != 0, 100 * (CHG / BASE), NA_real_)
  )
# -- END ADLB_BASELINE -- #

# -- BEGIN AWLO_AWHI -- #
adlb_windows <- adlb_base |>
  mutate(
    AWLO = case_when(
      VISITNUM == 1 ~ -28,
      VISITNUM == 2 ~ -14,
      VISITNUM == 4 ~ 12,
      VISITNUM == 5 ~ 26,
      VISITNUM == 6 ~ 54,
      VISITNUM == 7 ~ 82,
      VISITNUM == 8 ~ 110,
      VISITNUM == 9 ~ 166,
      VISITNUM == 10 ~ 250,
      VISITNUM == 11 ~ 362,
      VISITNUM == 12 ~ 370,
      VISITNUM == 13 ~ 377,
      VISITNUM == 14 ~ 390,
      TRUE ~ NA_real_
    ),
    AWHI = case_when(
      VISITNUM == 1 ~ -1,
      VISITNUM == 2 ~ -1,
      VISITNUM == 4 ~ 18,
      VISITNUM == 5 ~ 32,
      VISITNUM == 6 ~ 60,
      VISITNUM == 7 ~ 88,
      VISITNUM == 8 ~ 116,
      VISITNUM == 9 ~ 172,
      VISITNUM == 10 ~ 256,
      VISITNUM == 11 ~ 368,
      VISITNUM == 12 ~ 375,
      VISITNUM == 13 ~ 382,
      VISITNUM == 14 ~ 400,
      TRUE ~ NA_real_
    )
  )
# -- END AWLO_AWHI -- #

# -- BEGIN ANL01FL -- #
adlb <- adlb_windows |>
  mutate(
    # Analysis flag: within visit window and non-missing AVAL
    ANL01FL = if_else(
      !is.na(AVAL) & !is.na(AWLO) & !is.na(AWHI) &
        VISITNUM >= AWLO & VISITNUM <= AWHI,
      "Y", NA_character_
    )
  )
# -- END ANL01FL -- #
