# ********************************
# Program: adrs.R
# Generated by SpecGen (target = r)
# Oncology ADaM: ADRS (RECIST overall response) from SDTM rs
# ********************************
library(dplyr)

# -- BEGIN ADRS_PARAMCD -- #
adrs_ovr <- rs |>
  filter(RSTESTCD == "OVRLRESP") |>
  mutate(
    PARAMCD = "OVRLRESP",
    PARAM   = "Overall Response",
    AVALC   = trimws(RSORRES),
    # response ranking: lower = better (CR best)
    AVAL = case_when(
      toupper(AVALC) == "CR" ~ 1,
      toupper(AVALC) == "PR" ~ 2,
      toupper(AVALC) == "SD" ~ 3,
      toupper(AVALC) == "PD" ~ 4,
      toupper(AVALC) == "NE" ~ 5,
      TRUE ~ NA_real_
    )
  )
# -- END ADRS_PARAMCD -- #

# -- BEGIN ANL01FL_BOR -- #
adrs <- adrs_ovr |>
  group_by(USUBJID) |>
  arrange(AVAL, .by_group = TRUE) |>
  mutate(
    # flag the best (lowest-rank) response record per subject
    ANL01FL = if_else(row_number() == 1, "Y", NA_character_)
  ) |>
  ungroup()
# -- END ANL01FL_BOR -- #
