# ********************************
# Program: adtte.R
# Generated by SpecGen (target = r)
# Oncology ADaM: ADTTE (time-to-event PFS/OS) from ADSL
# ********************************
library(dplyr)

# -- BEGIN ADTTE_SETUP -- #
adtte_base <- adsl |>
  select(USUBJID, TRTSDT) |>
  mutate(STARTDT = TRTSDT)
# -- END ADTTE_SETUP -- #

# -- BEGIN PFS -- #
adtte_pfs <- adtte_base |>
  mutate(
    PARAMCD = "PFS",
    PARAM   = "Progression-Free Survival (days)",
    # TODO: set ADT = earliest of (progression date from ADRS PD),
    #       (death date from DS/DM); CNSR=0 if event, else ADT =
    #       last assessment date and CNSR=1
    ADT  = as.Date(NA),
    CNSR = NA_real_,
    AVAL = if_else(!is.na(ADT) & !is.na(STARTDT),
                   as.numeric(ADT - STARTDT) + 1, NA_real_)
  )
# -- END PFS -- #

# -- BEGIN OS -- #
adtte_os <- adtte_base |>
  mutate(
    PARAMCD = "OS",
    PARAM   = "Overall Survival (days)",
    # TODO: set ADT = death date (CNSR=0) or last-known-alive (CNSR=1)
    ADT  = as.Date(NA),
    CNSR = NA_real_,
    AVAL = if_else(!is.na(ADT) & !is.na(STARTDT),
                   as.numeric(ADT - STARTDT) + 1, NA_real_)
  )

adtte <- bind_rows(adtte_pfs, adtte_os)
# -- END OS -- #
