# ********************************
# Program: advs.R
# Generated by SpecGen (target = r)
# Findings ADaM: ADVS from SDTM vs
# ********************************
library(dplyr)

# -- BEGIN ADVS_PARAMCD -- #
advs_paramcd <- vs |>
  mutate(
    PARAMCD = case_when(
      VSTESTCD == "SYSBP" ~ "SYSBP",
      VSTESTCD == "DIABP" ~ "DIABP",
      VSTESTCD == "HR" ~ "HR",
      VSTESTCD == "TEMP" ~ "TEMP",
      VSTESTCD == "WEIGHT" ~ "WEIGHT",
      VSTESTCD == "HEIGHT" ~ "HEIGHT",
      TRUE ~ NA_character_
    ),
    PARAM = case_when(
      VSTESTCD == "SYSBP" ~ "Systolic Blood Pressure (mmHg)",
      VSTESTCD == "DIABP" ~ "Diastolic Blood Pressure (mmHg)",
      VSTESTCD == "HR" ~ "Heart Rate (beats/min)",
      VSTESTCD == "TEMP" ~ "Temperature (C)",
      VSTESTCD == "WEIGHT" ~ "Weight (kg)",
      VSTESTCD == "HEIGHT" ~ "Height (cm)",
      TRUE ~ NA_character_
    ),
    AVAL = VSSTRESN  # standardized numeric result
  )
# -- END ADVS_PARAMCD -- #

# -- BEGIN ADVS_BASELINE -- #
advs_baseline <- advs_paramcd |>
  filter(VISIT == "BASELINE") |>
  group_by(USUBJID, PARAMCD) |>
  summarise(BASE = dplyr::first(AVAL), .groups = "drop")

advs_base <- advs_paramcd |>
  left_join(advs_baseline, by = c("USUBJID", "PARAMCD")) |>
  mutate(
    CHG  = AVAL - BASE,
    PCHG = if_else(!is.na(BASE) & BASE != 0, 100 * (CHG / BASE), NA_real_)
  )
# -- END ADVS_BASELINE -- #

# -- BEGIN AWLO_AWHI -- #
advs_windows <- advs_base |>
  mutate(
    AWLO = case_when(
      VISITNUM == 1 ~ -28,
      VISITNUM == 2 ~ -14,
      VISITNUM == 4 ~ 12,
      VISITNUM == 5 ~ 26,
      VISITNUM == 6 ~ 54,
      VISITNUM == 7 ~ 82,
      VISITNUM == 8 ~ 110,
      VISITNUM == 9 ~ 166,
      VISITNUM == 10 ~ 250,
      VISITNUM == 11 ~ 362,
      VISITNUM == 12 ~ 370,
      VISITNUM == 13 ~ 377,
      VISITNUM == 14 ~ 390,
      TRUE ~ NA_real_
    ),
    AWHI = case_when(
      VISITNUM == 1 ~ -1,
      VISITNUM == 2 ~ -1,
      VISITNUM == 4 ~ 18,
      VISITNUM == 5 ~ 32,
      VISITNUM == 6 ~ 60,
      VISITNUM == 7 ~ 88,
      VISITNUM == 8 ~ 116,
      VISITNUM == 9 ~ 172,
      VISITNUM == 10 ~ 256,
      VISITNUM == 11 ~ 368,
      VISITNUM == 12 ~ 375,
      VISITNUM == 13 ~ 382,
      VISITNUM == 14 ~ 400,
      TRUE ~ NA_real_
    )
  )
# -- END AWLO_AWHI -- #

# -- BEGIN ANL01FL -- #
advs <- advs_windows |>
  mutate(
    # Analysis flag: within visit window and non-missing AVAL
    ANL01FL = if_else(
      !is.na(AVAL) & !is.na(AWLO) & !is.na(AWHI) &
        VISITNUM >= AWLO & VISITNUM <= AWHI,
      "Y", NA_character_
    )
  )
# -- END ANL01FL -- #
