/* ********************************* */
/* Program: advs_spec.sas */
/* Generated by SpecGen (adam_bds_assembler.py) */
/* ********************************* */

data advs;
    set vs;  /* raw SDTM VS domain — every ADaM-only
       variable below (PARAMCD/AVAL/BASE/..., ADSL merges, date conversions,
       analysis flags) is derived by its own spec row, not pre-built */

/*-- BEGIN PARAMCD --*/
/* Derive PARAMCD from VSTESTCD */
length PARAMCD $8;
PARAMCD = VSTESTCD;
label PARAMCD = "Parameter Code";
/*-- END PARAMCD --*/

/*-- BEGIN PARAM --*/
/* Derive PARAM from VSTESTCD */
length PARAM $40;
label PARAM = "Parameter";
if VSTESTCD = 'SYSBP' then PARAM = 'Systolic Blood Pressure (mmHg)';
else if VSTESTCD = 'DIABP' then PARAM = 'Diastolic Blood Pressure (mmHg)';
else if VSTESTCD = 'PULSE' then PARAM = 'Pulse Rate (beats/min)';
else call missing(PARAM);
/*-- END PARAM --*/

/*-- BEGIN AVAL --*/
/* Derive AVAL from VSSTRESN */
length AVAL 8;
label AVAL = "Analysis Value";
AVAL = VSSTRESN;
/*-- END AVAL --*/

/*-- BEGIN ANL01FL --*/
/* Derive ANL01FL: Analysis Flag 01 */
length ANL01FL $1;
label ANL01FL = "Analysis Flag 01";
if not missing(AVAL) then ANL01FL = 'Y';
/*-- END ANL01FL --*/

run;
